# Sample Problem 

Given the following *imperative* program, implement the same functionality using two other different programming paradigms. 

## Original Imperative Program

In [5]:
import numpy as np

A = np.arange(9).reshape( 3, 3 )
B = np.arange(9).reshape( 3, 3 )
N = A.shape[0]
C = np.zeros( (N,N), dtype=int )
for i in range(N) :
    for j in range(N) :
        for k in range( N ) :
            C[i,j] += A[i,k] * B[k,j]
C

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## Solution: Using List Comprehension (Functional Paradigm)

In [12]:
from functools import reduce

C = [reduce( lambda x,y : x+y, A[i,:]*B[:,j] )  for i in range(N) for j in range(N)]
C = np.array(C).reshape( (3,3) )
C

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## Solution: Using Ensum (Array Paradigm)

In [4]:
C = np.einsum('ik, kj->ij', A, B)
C

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])